spring:
  application:
    name: ms-matricula

  datasource:
    url: jdbc:h2:mem:ms_matricula;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update        # o create-drop si quieres limpiar en cada arranque
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
  sql:
    init:
      mode: always            # si usas schema.sql/data.sql y quieres que se apliquen
  h2:
    console:
      enabled: true
      path: /h2-console       # entra a http://localhost:7569/h2-console y usa la URL arriba

server:
  port: 7569

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8094/eureka
  instance:
    hostname: localhost
